version: '3.5'
  
services:
  postgres:
    container_name: postgres_container
    image: orboan/postgreshr:11.14
    environment:
      POSTGRES_USER: ${NB_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pluralcamp}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - data:/data/postgres
      - /var/run/postgresql:/var/run/postgresql
    ports:
      - "5432:5432"    

  pgadmin:
    container_name: pgadmin_container
    #image: dpage/pgadmin4:latest
    build: .
    environment:
      PGADMIN_DEFAULT_EMAIL: "${NB_USER}@ilg.cat"
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pluralcamp}
      PGADMIN_DISABLE_POSTFIX: 'True'
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_LISTEN_PORT: '80'
      PGADMIN_PORT: "${pgport}"
      PGADMIN_CONFIG_X_FRAME_OPTIONS: '""'
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: '2'
      PGADMIN_CONFIG_X_CONTENT_TYPE_OPTIONS: '""'
    volumes:
       - pgadmin_data:/var/lib/pgadmin
       - pgadmin_config:/pgadmin4
    ports:
      - "${pgport:-5050}:80"

networks:
  default:
    external: true
    name: "${net:-entornet}"

volumes:
    data:
    pgadmin_data:
    pgadmin_config:
